# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_auto_20171021_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=200)),
                ('lastnames', models.CharField(blank=True, max_length=200, null=True)),
                ('identification_number', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_subjects', to='courses.Subject')),
            ],
        ),
    ]
