# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20171021_1250'),
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='subjects',
        ),
        migrations.AddField(
            model_name='professor',
            name='subjects',
            field=models.ManyToManyField(related_name='professor_subjects', to='courses.Subject'),
        ),
    ]
