# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-14 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0004_auto_20171214_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
