# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
