# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20171014_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='courses.Department')),
            ],
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='department',
        ),
        migrations.DeleteModel(
            name='Instrument',
        ),
    ]
