# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20171021_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_deparment', to='courses.Department'),
        ),
    ]
