# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-14 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lastnames',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='names',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
